version: 2

mkdocs:
  configuration: mkdocs.yml

markdown_extensions:
    - toc:
	permalink:
        baselevel: 6

python:
   version: 3.8
   install:
     - requirements: docs/requirements.txt
   system_packages: true
